package Modelo;
// Generated 23/07/2019 18:03:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codCli;
     private String nomCli;
     private String apeCli;
     private String sexoCli;
     private String dniCli;
     private String telCli;
     private String rucCli;
     private String emailCli;
     private String dirCli;
     private String tipoCli;
     private Set facturas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int codCli, String nomCli, String apeCli, String sexoCli, String dniCli, String telCli, String rucCli, String emailCli, String dirCli) {
        this.codCli = codCli;
        this.nomCli = nomCli;
        this.apeCli = apeCli;
        this.sexoCli = sexoCli;
        this.dniCli = dniCli;
        this.telCli = telCli;
        this.rucCli = rucCli;
        this.emailCli = emailCli;
        this.dirCli = dirCli;
    }
    public Cliente(int codCli, String nomCli, String apeCli, String sexoCli, String dniCli, String telCli, String rucCli, String emailCli, String dirCli, String tipoCli, Set facturas) {
       this.codCli = codCli;
       this.nomCli = nomCli;
       this.apeCli = apeCli;
       this.sexoCli = sexoCli;
       this.dniCli = dniCli;
       this.telCli = telCli;
       this.rucCli = rucCli;
       this.emailCli = emailCli;
       this.dirCli = dirCli;
       this.tipoCli = tipoCli;
       this.facturas = facturas;
    }
   
    public int getCodCli() {
        return this.codCli;
    }
    
    public void setCodCli(int codCli) {
        this.codCli = codCli;
    }
    public String getNomCli() {
        return this.nomCli;
    }
    
    public void setNomCli(String nomCli) {
        this.nomCli = nomCli;
    }
    public String getApeCli() {
        return this.apeCli;
    }
    
    public void setApeCli(String apeCli) {
        this.apeCli = apeCli;
    }
    public String getSexoCli() {
        return this.sexoCli;
    }
    
    public void setSexoCli(String sexoCli) {
        this.sexoCli = sexoCli;
    }
    public String getDniCli() {
        return this.dniCli;
    }
    
    public void setDniCli(String dniCli) {
        this.dniCli = dniCli;
    }
    public String getTelCli() {
        return this.telCli;
    }
    
    public void setTelCli(String telCli) {
        this.telCli = telCli;
    }
    public String getRucCli() {
        return this.rucCli;
    }
    
    public void setRucCli(String rucCli) {
        this.rucCli = rucCli;
    }
    public String getEmailCli() {
        return this.emailCli;
    }
    
    public void setEmailCli(String emailCli) {
        this.emailCli = emailCli;
    }
    public String getDirCli() {
        return this.dirCli;
    }
    
    public void setDirCli(String dirCli) {
        this.dirCli = dirCli;
    }
    public String getTipoCli() {
        return this.tipoCli;
    }
    
    public void setTipoCli(String tipoCli) {
        this.tipoCli = tipoCli;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


