package Modelo;
// Generated 23/07/2019 18:03:30 by Hibernate Tools 4.3.1



/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private int iddetalle;
     private Factura factura;
     private Producto producto;
     private String desPro;
     private String cantPro;
     private String preUnit;
     private String preTot;

    public Detallefactura() {
    }

    public Detallefactura(int iddetalle, Factura factura, Producto producto, String desPro, String cantPro, String preUnit, String preTot) {
       this.iddetalle = iddetalle;
       this.factura = factura;
       this.producto = producto;
       this.desPro = desPro;
       this.cantPro = cantPro;
       this.preUnit = preUnit;
       this.preTot = preTot;
    }
   
    public int getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getDesPro() {
        return this.desPro;
    }
    
    public void setDesPro(String desPro) {
        this.desPro = desPro;
    }
    public String getCantPro() {
        return this.cantPro;
    }
    
    public void setCantPro(String cantPro) {
        this.cantPro = cantPro;
    }
    public String getPreUnit() {
        return this.preUnit;
    }
    
    public void setPreUnit(String preUnit) {
        this.preUnit = preUnit;
    }
    public String getPreTot() {
        return this.preTot;
    }
    
    public void setPreTot(String preTot) {
        this.preTot = preTot;
    }




}


