package Modelo;
// Generated 23/07/2019 14:36:50 by Hibernate Tools 4.3.1



/**
 * Detallefacturac generated by hbm2java
 */
public class Detallefacturac  implements java.io.Serializable {


     private int iddetalle;
     private Facturac facturac;
     private Producto producto;
     private String desPro;
     private String cantPro;
     private String preUnit;
     private String preTot;

    public Detallefacturac() {
    }

	
    public Detallefacturac(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Detallefacturac(int iddetalle, Facturac facturac, Producto producto, String desPro, String cantPro, String preUnit, String preTot) {
       this.iddetalle = iddetalle;
       this.facturac = facturac;
       this.producto = producto;
       this.desPro = desPro;
       this.cantPro = cantPro;
       this.preUnit = preUnit;
       this.preTot = preTot;
    }
   
    public int getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Facturac getFacturac() {
        return this.facturac;
    }
    
    public void setFacturac(Facturac facturac) {
        this.facturac = facturac;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getDesPro() {
        return this.desPro;
    }
    
    public void setDesPro(String desPro) {
        this.desPro = desPro;
    }
    public String getCantPro() {
        return this.cantPro;
    }
    
    public void setCantPro(String cantPro) {
        this.cantPro = cantPro;
    }
    public String getPreUnit() {
        return this.preUnit;
    }
    
    public void setPreUnit(String preUnit) {
        this.preUnit = preUnit;
    }
    public String getPreTot() {
        return this.preTot;
    }
    
    public void setPreTot(String preTot) {
        this.preTot = preTot;
    }




}


