package Modelo;
// Generated 23/07/2019 14:36:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facturac generated by hbm2java
 */
public class Facturac  implements java.io.Serializable {


     private String numFac;
     private Proveedor proveedor;
     private String subtotal;
     private String iva;
     private String total;
     private String fecFac;
     private String estado;
     private Set detallefacturacs = new HashSet(0);

    public Facturac() {
    }

	
    public Facturac(String numFac) {
        this.numFac = numFac;
    }
    public Facturac(String numFac, Proveedor proveedor, String subtotal, String iva, String total, String fecFac, String estado, Set detallefacturacs) {
       this.numFac = numFac;
       this.proveedor = proveedor;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.fecFac = fecFac;
       this.estado = estado;
       this.detallefacturacs = detallefacturacs;
    }
   
    public String getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(String numFac) {
        this.numFac = numFac;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getFecFac() {
        return this.fecFac;
    }
    
    public void setFecFac(String fecFac) {
        this.fecFac = fecFac;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetallefacturacs() {
        return this.detallefacturacs;
    }
    
    public void setDetallefacturacs(Set detallefacturacs) {
        this.detallefacturacs = detallefacturacs;
    }




}


