package Modelo;
// Generated 23/07/2019 18:03:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int numFac;
     private Cliente cliente;
     private String rucCli;
     private String subtotal;
     private String igv;
     private String total;
     private String fecFac;
     private String estado;
     private Set detallefacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int numFac, Cliente cliente, String rucCli, String subtotal, String igv, String total, String fecFac) {
        this.numFac = numFac;
        this.cliente = cliente;
        this.rucCli = rucCli;
        this.subtotal = subtotal;
        this.igv = igv;
        this.total = total;
        this.fecFac = fecFac;
    }
    public Factura(int numFac, Cliente cliente, String rucCli, String subtotal, String igv, String total, String fecFac, String estado, Set detallefacturas) {
       this.numFac = numFac;
       this.cliente = cliente;
       this.rucCli = rucCli;
       this.subtotal = subtotal;
       this.igv = igv;
       this.total = total;
       this.fecFac = fecFac;
       this.estado = estado;
       this.detallefacturas = detallefacturas;
    }
   
    public int getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(int numFac) {
        this.numFac = numFac;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getRucCli() {
        return this.rucCli;
    }
    
    public void setRucCli(String rucCli) {
        this.rucCli = rucCli;
    }
    public String getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }
    public String getIgv() {
        return this.igv;
    }
    
    public void setIgv(String igv) {
        this.igv = igv;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getFecFac() {
        return this.fecFac;
    }
    
    public void setFecFac(String fecFac) {
        this.fecFac = fecFac;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


