package Modelo;
// Generated 23/07/2019 14:36:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoprod generated by hbm2java
 */
public class Tipoprod  implements java.io.Serializable {


     private int idtipoprod;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Tipoprod() {
    }

	
    public Tipoprod(int idtipoprod) {
        this.idtipoprod = idtipoprod;
    }
    public Tipoprod(int idtipoprod, String descripcion, Set productos) {
       this.idtipoprod = idtipoprod;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdtipoprod() {
        return this.idtipoprod;
    }
    
    public void setIdtipoprod(int idtipoprod) {
        this.idtipoprod = idtipoprod;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


