package Modelo;
// Generated 23/07/2019 14:36:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Umedida generated by hbm2java
 */
public class Umedida  implements java.io.Serializable {


     private String codmedida;
     private String nommedida;
     private Set productos = new HashSet(0);

    public Umedida() {
    }

	
    public Umedida(String codmedida) {
        this.codmedida = codmedida;
    }
    public Umedida(String codmedida, String nommedida, Set productos) {
       this.codmedida = codmedida;
       this.nommedida = nommedida;
       this.productos = productos;
    }

    public Umedida(String codmedida, String nommedida) {
        this.codmedida = codmedida;
        this.nommedida = nommedida;
    }
   
    public String getCodmedida() {
        return this.codmedida;
    }
    
    public void setCodmedida(String codmedida) {
        this.codmedida = codmedida;
    }
    public String getNommedida() {
        return this.nommedida;
    }
    
    public void setNommedida(String nommedida) {
        this.nommedida = nommedida;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


