package Modelo;
// Generated 23/07/2019 14:36:50 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String login;
     private String clave;
     private String apenom;
     private Character admin;

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, String login, String clave, String apenom, Character admin) {
       this.idusuario = idusuario;
       this.login = login;
       this.clave = clave;
       this.apenom = apenom;
       this.admin = admin;
    }

    public Usuario(String login, String clave, String apenom, Character admin) {
        this.login = login;
        this.clave = clave;
        this.apenom = apenom;
        this.admin = admin;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getApenom() {
        return this.apenom;
    }
    
    public void setApenom(String apenom) {
        this.apenom = apenom;
    }
    public Character getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Character admin) {
        this.admin = admin;
    }




}


